on:
  push:
    branches:
      - "release-robocorp-logging"
    tags:
      - "robocorp-logging-*"

name: Deploy - Robocorp Logging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    # Build Python version
    - name: Install deps
      run: pip install --upgrade pip fire twine wheel setuptools
      
    - name: Embed output view in index.py
      run: |
        python -m dev build-output-view
        # python -m dev check-no-git-changes -- disabled because
        # building in prod makes changes appear even if the entry
        # code is the same. 

    - name: Build wheel
      working-directory: ./src
      run: |
        cp ../README.md ./README.md
        python setup.py sdist bdist_wheel --universal
        
    - name: Check tag version
      run: python -m dev check-tag-version
      
    - name: Upload to PyPI
      working-directory: ./src
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
