[tool.robo]
name = "RPA Challenge"
description = "A simple example robot that solves the RPA Challenge"
python = "3.9.13"

[tool.robo.dependencies]
robocorp-tasks="0.1.4"
robocorp-browser="0.2.0"
robocorp-excel="0.2.0"
robocorp-http="0.2.0"

[tool.robo.dev-dependencies]
ruff="0.0.260"
black="23.3.0"
