policy:
  - section:
    - id: [ components ]
      block-list: [ 'Other' ]
      label:
        - name: 'Action Server'
          keys: [ 'action_server', 'actions' ]
        - name: 'Library'
          keys: [ 'browser', 'desktop', 'excel', 'log', 'log_pytest', 'meta', 'storage', 'tasks', 'vault', 'windows', 'workitems' ]
        - name: 'robocorp'
          keys: [ 'meta' ]
        - name: 'robocorp-actions'
          keys: [ 'actions' ]
        - name: 'robocorp-browser'
          keys: [ 'browser' ]
        - name: 'robocorp-desktop'
          keys: [ 'desktop' ]
        - name: 'robocorp-excel'
          keys: [ 'excel' ]
        - name: 'robocorp-log'
          keys: [ 'log', 'log_pytest' ]
        - name: 'robocorp-storage'
          keys: [ 'storage' ]
        - name: 'robocorp-tasks'
          keys: [ 'tasks' ]
        - name: 'robocorp-vault'
          keys: [ 'vault' ]
        - name: 'robocorp-windows'
          keys: [ 'windows' ]
        - name: 'robocorp-workitems'
          keys: [ 'workitems' ]
