name: Log Lint

on:
  push:
    branches:
      - "master"
      - "wip"
    paths:
      - "log/**"
      - ".github/workflows/log_lint.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "log/**"
      - ".github/workflows/log_lint.yml"

defaults:
  run:
    working-directory: './log'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'

      - name: Install project
        run: poetry install

      - name: Setup node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@robocorp"
          
      - name: Install prettier
        run: |
          npm install -g prettier@2.4.1

      - name: TS Format (yarn prettier --write **/*.ts to format files locally)
        working-directory: ./log/output-webview/
        run: prettier --check **/*.ts

      - name: Test React log
        working-directory: ./log/output-react/
        # npm run test:lint -- linting not done, just prettier/types.
        run: |
          npm ci
          npm run test:prettier
          npm run test:types
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        
      - name: Black check
        run: |
          poetry run black --check src tests --exclude="_index\.py|_index_v2\.py"

      - name: mypy robocorp-log
        run: |
          poetry run mypy --follow-imports=silent --show-column-numbers --namespace-packages --explicit-package-bases src tests


