name: Tasks Tests

on:
  push:
    paths:
      - "tasks/**"
      - "log/**"
      - ".github/workflows/tasks_tests.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "tasks/**"
      - "log/**"
      - ".github/workflows/tasks_tests.yml"

defaults:
  run:
    working-directory: './tasks'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py39-logindev",
          "windows-py310",
        ]

        include:
          - name: "ubuntu-py39-logindev"
            python: "3.9"
            os: ubuntu-latest
            PATH_SEPARATOR: ":"
          - name: "windows-py310"
            python: "3.10"
            os: windows-latest
            PATH_SEPARATOR: ";"


    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      
    # Use poetry
    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'poetry'

    - name: Install project
      run: poetry install
      
    # Uncomment setup below to use the dev version of robocorp-log.    
    - name: Print robocorp-log info and build the output view.
      if: contains(matrix.name, '-logindev')
      env:
        PYTHONPATH: ./src${{ matrix.PATH_SEPARATOR }}../log/src
      run: |
        python -c "import sys;print('\n'.join(str(x) for x in sys.path))"
        python -c "from robocorp import log;print(log.__file__)"
        cd ../log
        poetry run inv build-output-view

    - name: Test (dev)
      if: contains(matrix.name, '-logindev')
      env:
        PYTHONPATH: ./src${{ matrix.PATH_SEPARATOR }}../log/src
        GITHUB_ACTIONS_MATRIX_NAME: ${{ matrix.name }}
      run: poetry run pytest -rfE -vv tests/tasks_tests

    - name: Test (log from pypi)
      env:
        GITHUB_ACTIONS_MATRIX_NAME: ${{ matrix.name }}
      if: contains(matrix.name, '-logindev') == false
      run: poetry run pytest -rfE -vv tests/tasks_tests

